// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkxjhtmnxtmpctqlkdrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFreGpodG1ueHRtcGN0cWxrZHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMDA4MzMsImV4cCI6MjA3ODg3NjgzM30.b913pppuet_tp5zzHNQy1Jt-rrbO66S3h0YTn_04pg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});